version: "3"

services:
  mongo:
    image: mongo:5.0.5
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongoui
    ports:
      - "8080:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=dev_admin
      - ME_CONFIG_BASICAUTH_PASSWORD=dev_password

volumes:
  mongo_data:
