version: "3:8"

services:
  mongo:
    image: mongo:5.0.6-focal
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongoui
    ports:
      - "8080:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=dev_admin
      - ME_CONFIG_BASICAUTH_PASSWORD=dev_password
    networks:
      - mongo-network

volumes:
  mongo_data:

networks:
  mongo-network:
    driver: bridge
