version: "3"

services:
  rabbit:
    container_name: rabbit_dev
    image: rabbitmq:3.10.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=dev_admin
      - RABBITMQ_DEFAULT_PASS=dev_password
